name: KoChat
version: '${version}'
main: me.akkih.kochat.KoChat
api-version: 1.19
author: Akkih
description: A plugin to enhance your chatting experience on Minecraft!
website: https://github.com/Akkihiko/KoChat
